export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SET_TRANSACTION_CONFIRMED = 'SET_TRANSACTION_CONFIRMED';
export const SET_WAITING_FOR_TRANSACTION_SUBMIT = 'SET_WAITING_FOR_TRANSACTION_SUBMIT';
export const STATUS_PENDING = 'STATUS_PENDING';
export const STATUS_CONFIRMED = 'STATUS_CONFIRMED';
export const ADD_ALL_FRAC = 'ADD_ALL_FRAC';
export const TRANSACTION_TYPE = {
  FRACTIONATE: 'FRACTIONATE',
  FRACTIONATE_TOKEN_APPROVE: 'FRACTIONATE_TOKEN_APPROVE',
  FRACTIONATE_NFT_APPROVE: 'FRACTIONATE_NFT_APPROVE',
  FRACTIONATE_AUCTION_BID: 'FRACTIONATE_AUCTION_BID',
  FRACTIONATE_SETTLE_AUCTION: 'FRACTIONATE_SETTLE_AUCTION',
}
export const RESET_FRACTIONATE_TRANSACTION = 'RESET_FRACTIONATE_TRANSACTION';
export const SET_FRACS_FETCHING = 'SET_FRACS_FETCHING';
