export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SET_TRANSACTION_CONFIRMED = 'SET_TRANSACTION_CONFIRMED';
export const STATUS_PENDING = 'STATUS_PENDING';
export const STATUS_CONFIRMED = 'STATUS_CONFIRMED';
