export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SET_TRANSACTION_CONFIRMED = 'SET_TRANSACTION_CONFIRMED';
export const SET_WAITING_FOR_TRANSACTION_SUBMIT = 'SET_WAITING_FOR_TRANSACTION_SUBMIT';
export const STATUS_PENDING = 'STATUS_PENDING';
export const STATUS_CONFIRMED = 'STATUS_CONFIRMED';
export const TRANSACTION_TYPE = {
  FRACTIONATE: 'FRACTIONATE',
  TOKEN_APPROVE: 'TOKEN_APPROVE',
}
