export const SET_CONNECTED_WALLET = 'SET_CONNECTED_WALLET';
export const SET_WALLET_CONNECTING = 'SET_WALLET_CONNECTING';
export const SET_WALLET_NFT_ASSETS_FETCHING = 'SET_WALLET_NFT_ASSETS_FETCHING';
export const SET_WALLET_NFT_ASSETS = 'SET_WALLET_NFT_ASSETS';
