export const SET_CONNECTED_WALLET = 'SET_CONNECTED_WALLET';
export const SET_WALLET_CONNECTING = 'SET_WALLET_CONNECTING';
export const SET_WALLET_NFT_ASSETS_FETCHING = 'SET_WALLET_NFT_ASSETS_FETCHING';
export const SET_WALLET_NFT_ASSETS = 'SET_WALLET_NFT_ASSETS';
export const SET_TOKEN_BALANCE = 'SET_TOKEN_BALANCE';
export const SET_OPENSEA_NFT_ASSET_FETCHING = 'SET_OPENSEA_NFT_ASSET_FETCHING';
export const SET_OPENSEA_NFT_ASSET = 'SET_OPENSEA_NFT_ASSET';
